### ISSUE TITLE
Folder mismatch on Repair (is verify EXACT_PATH based on a sanitized API value instead of the actual install location?)

### ISSUE THREAD

**Issue by instinctualjealousy** [hawkeye116477/playnite-nile-plugin#8]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-nile-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.0.3.25976

### Nile Launcher version

1.1.2

### Bug description

I noticed this issue with a game that had been installed prior with Amazon Games. Endling: Extinction is Forever.

It was installed to `Endling - Extinction is Forever`, I did a Repair on it to test the functionality of both Playnite and Nile. It was taking forever- I found out that it was actually pointing the verify operation to a different folder, `Endling Extinction is Forever`, and since the game files didn't exist there, it was redownloading them all as per verify's rules. I migrated the games over with the plugin's functionality, and Nile's installed.json correctly pointed to `Endling - Extinction is Forever`... so I have no clue how it determined the folder to be different than the current install location. I imagine some logic assigning a game folder name for newly installed games is getting used incorrectly in this operation?

### Relevant log

15-11 11:06:53.229|DEBUG|NileLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\amazon-nile\current\nile.exe verify amzn1.adg.product.21965245-d668-4a8f-818a-38133698587b --path "D:\AmazonLibrary\Endling Extinction is Forever" --max-workers 4

**Comment by hawkeye116477** [comment]
Yeah, I see the problem. Will be fixed in next update.
